---
title: "&#39;Throw &#39;陳述式不能省略運算元外的 &#39;Catch &#39;陳述式或內部 &#39;最後 &#39;陳述式"
ms.date: 07/20/2015
ms.prod: .net
ms.technology: devlang-visual-basic
ms.topic: article
f1_keywords:
- vbc30666
- bc30666
helpviewer_keywords: BC30666
ms.assetid: a208a6ea-0e36-4bf1-8984-4de1a0e38a2a
caps.latest.revision: "8"
author: dotnet-bot
ms.author: dotnetcontent
ms.openlocfilehash: 5fa3be0ca47a4158b3abeef9801148e3f19d3b36
ms.sourcegitcommit: c0dd436f6f8f44dc80dc43b07f6841a00b74b23f
ms.translationtype: MT
ms.contentlocale: zh-TW
ms.lasthandoff: 01/19/2018
---
# <a name="39throw39-statement-cannot-omit-operand-outside-a-39catch39-statement-or-inside-a-39finally39-statement"></a>&#39;Throw &#39;陳述式不能省略運算元外的 &#39;Catch &#39;陳述式或內部 &#39;最後 &#39;陳述式
`Throw` 陳述式外的 `Catch` 陳述式必須提供例外狀況物件的名稱。  
  
 **錯誤 ID：** BC30666  
  
## <a name="to-correct-this-error"></a>更正這個錯誤  
  
1.  指定衍生自 `System.Exception`之例外狀況物件的名稱。  
  
2.  重建您的程式碼，讓 `Throw` 陳述式位於 `Catch` 區塊內。  
  
## <a name="see-also"></a>請參閱  
 [Throw 陳述式](../../visual-basic/language-reference/statements/throw-statement.md)  
 [Try...Catch...Finally 陳述式](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)  
 [在 Visual Basic 中的例外狀況類別](http://msdn.microsoft.com/library/9aac396f-34ca-4afb-8e6c-e523cb690ba9)  
 [例外狀況和 Visual Basic 中的錯誤處理](http://msdn.microsoft.com/library/3e351e73-cf23-40ab-8b60-05794160529e)
