---
title: "&#39;Catch &#39;區塊永遠不會執行到，因為 &#39;&lt;name1&gt;&#39; 繼承自 &#39;&lt;name2&gt;&#39;"
ms.date: 07/20/2015
ms.prod: .net
ms.technology: devlang-visual-basic
ms.topic: article
f1_keywords:
- BC42029
- vbc42029
helpviewer_keywords: BC42029
ms.assetid: 4bc84a84-ec7e-49db-8794-4fb71d36d5c0
caps.latest.revision: "12"
author: dotnet-bot
ms.author: dotnetcontent
ms.openlocfilehash: 699f2ef1ff9d554bb9203631017b424ab887ab93
ms.sourcegitcommit: c0dd436f6f8f44dc80dc43b07f6841a00b74b23f
ms.translationtype: MT
ms.contentlocale: zh-TW
ms.lasthandoff: 01/19/2018
---
# <a name="39catch39-block-never-reached-because-39ltname1gt39-inherits-from-39ltname2gt39"></a>&#39;Catch &#39;區塊永遠不會執行到，因為 &#39;&lt;name1&gt;&#39; 繼承自 &#39;&lt;name2&gt;&#39;
永遠不會執行到程式碼內的 `Catch` 區塊。  
  
 根據預設，這個訊息是一個警告。 如需隱藏警告或將警告視為錯誤的詳細資訊，請參閱[Visual Basic 中的 設定警告](/visualstudio/ide/configuring-warnings-in-visual-basic)。  
  
 **錯誤 ID︰** BC42029  
  
## <a name="to-correct-this-error"></a>更正這個錯誤  
  
-   請移除多餘的 `Catch` 區塊。  
  
## <a name="see-also"></a>請參閱  
 [如何： 測試程式碼使用 Try...在 Visual Basic 的 catch 區塊](http://msdn.microsoft.com/library/8368e205-ed73-4185-a247-af84fb4fafa9)  
 [Try...Catch...Finally 陳述式](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
